package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudent;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.ClassStudentDao;
 
 
/**
 * DAO for table: ClassStudent.
 * @author autogenerated
 */
@Repository
public class ClassStudentDaoImpl extends GenericHibernateDaoImpl<ClassStudent, String> implements ClassStudentDao {
	
	/** Constructor method. */
		public ClassStudentDaoImpl() {
			super(ClassStudent.class);
		}
	}

