package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.SectionHasStaffHasRolePK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.SectionHasStaffHasRolePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: SectionHasStaffHasRolePK.
 * @author autogenerated
 */
@Repository
public class SectionHasStaffHasRolePKDaoImpl extends GenericHibernateDaoImpl<SectionHasStaffHasRolePK, Serializable> implements SectionHasStaffHasRolePKDao {
	
	/** Constructor method. */
		public SectionHasStaffHasRolePKDaoImpl() {
			super(SectionHasStaffHasRolePK.class);
		}
	}

