package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.SectionHasStaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.SectionHasStaffHasRoleDao;
import org.yarlithub.yschool.model.obj.yschoolLite.SectionHasStaffHasRolePK;
 
/**
 * DAO for table: SectionHasStaffHasRole.
 * @author autogenerated
 */
@Repository
public class SectionHasStaffHasRoleDaoImpl extends GenericHibernateDaoImpl<SectionHasStaffHasRole, SectionHasStaffHasRolePK> implements SectionHasStaffHasRoleDao {
	
	/** Constructor method. */
		public SectionHasStaffHasRoleDaoImpl() {
			super(SectionHasStaffHasRole.class);
		}
	}

