package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.Staff;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.StaffDao;
 
 
/**
 * DAO for table: Staff.
 * @author autogenerated
 */
@Repository
public class StaffDaoImpl extends GenericHibernateDaoImpl<Staff, Integer> implements StaffDao {
	
	/** Constructor method. */
		public StaffDaoImpl() {
			super(Staff.class);
		}
	}

