package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.Student;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.StudentDao;
 
 
/**
 * DAO for table: Student.
 * @author autogenerated
 */
@Repository
public class StudentDaoImpl extends GenericHibernateDaoImpl<Student, Integer> implements StudentDao {
	
	/** Constructor method. */
		public StudentDaoImpl() {
			super(Student.class);
		}
	}

