package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.Subject;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.SubjectDao;
 
 
/**
 * DAO for table: Subject.
 * @author autogenerated
 */
@Repository
public class SubjectDaoImpl extends GenericHibernateDaoImpl<Subject, Integer> implements SubjectDao {
	
	/** Constructor method. */
		public SubjectDaoImpl() {
			super(Subject.class);
		}
	}

