package org.yarlithub.yschool.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschool.ClassStudent;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschool.ClassStudentDao;
 
 
/**
 * DAO for table: ClassStudent.
 * @author autogenerated
 */
@Repository
public class ClassStudentDaoImpl extends GenericHibernateDaoImpl<ClassStudent, Integer> implements ClassStudentDao {
	
	/** Constructor method. */
		public ClassStudentDaoImpl() {
			super(ClassStudent.class);
		}
	}

