package org.yarlithub.yschool.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschool.ClassSubjectHasStaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschool.ClassSubjectHasStaffHasRoleDao;
import org.yarlithub.yschool.model.obj.yschool.ClassSubjectHasStaffHasRolePK;
 
/**
 * DAO for table: ClassSubjectHasStaffHasRole.
 * @author autogenerated
 */
@Repository
public class ClassSubjectHasStaffHasRoleDaoImpl extends GenericHibernateDaoImpl<ClassSubjectHasStaffHasRole, ClassSubjectHasStaffHasRolePK> implements ClassSubjectHasStaffHasRoleDao {
	
	/** Constructor method. */
		public ClassSubjectHasStaffHasRoleDaoImpl() {
			super(ClassSubjectHasStaffHasRole.class);
		}
	}

