package org.yarlithub.yschool.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschool.Marks;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschool.MarksDao;
 
 
/**
 * DAO for table: Marks.
 * @author autogenerated
 */
@Repository
public class MarksDaoImpl extends GenericHibernateDaoImpl<Marks, Integer> implements MarksDao {
	
	/** Constructor method. */
		public MarksDaoImpl() {
			super(Marks.class);
		}
	}

