package org.yarlithub.yschool.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschool.SchoolHasStaffHasRolePK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschool.SchoolHasStaffHasRolePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: SchoolHasStaffHasRolePK.
 * @author autogenerated
 */
@Repository
public class SchoolHasStaffHasRolePKDaoImpl extends GenericHibernateDaoImpl<SchoolHasStaffHasRolePK, Serializable> implements SchoolHasStaffHasRolePKDao {
	
	/** Constructor method. */
		public SchoolHasStaffHasRolePKDaoImpl() {
			super(SchoolHasStaffHasRolePK.class);
		}
	}

