package org.yarlithub.yschool.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschool.SchoolHasStaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschool.SchoolHasStaffHasRoleDao;
import org.yarlithub.yschool.model.obj.yschool.SchoolHasStaffHasRolePK;
 
/**
 * DAO for table: SchoolHasStaffHasRole.
 * @author autogenerated
 */
@Repository
public class SchoolHasStaffHasRoleDaoImpl extends GenericHibernateDaoImpl<SchoolHasStaffHasRole, SchoolHasStaffHasRolePK> implements SchoolHasStaffHasRoleDao {
	
	/** Constructor method. */
		public SchoolHasStaffHasRoleDaoImpl() {
			super(SchoolHasStaffHasRole.class);
		}
	}

