package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaff;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaffPK;
/**
 * DAO interface for table: ClassStaff.
 * @author autogenerated
 */
public interface ClassStaffDao extends GenericDAO<ClassStaff,  ClassStaffPK>  {
	// constructor only
}

