package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudent;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudentPK;
/**
 * DAO interface for table: ClassStudent.
 * @author autogenerated
 */
public interface ClassStudentDao extends GenericDAO<ClassStudent,  ClassStudentPK>  {
	// constructor only
}

