package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.Classroom;
 
/**
 * DAO interface for table: Classroom.
 * @author autogenerated
 */
public interface ClassroomDao extends GenericDAO<Classroom,  Integer>  {
	// constructor only
}

