package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudentPK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassStudentPK.
 * @author autogenerated
 */
public interface ClassStudentPKDao extends GenericDAO<ClassStudentPK,  Serializable>  {
	// constructor only
}

