package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.Marks;
 
/**
 * DAO interface for table: Marks.
 * @author autogenerated
 */
public interface MarksDao extends GenericDAO<Marks,  Integer>  {
	// constructor only
}

