package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.School;
 
/**
 * DAO interface for table: School.
 * @author autogenerated
 */
public interface SchoolDao extends GenericDAO<School,  Integer>  {
	// constructor only
}

