package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubject;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubjectPK;
/**
 * DAO interface for table: StudentHasOptionalsubject.
 * @author autogenerated
 */
public interface StudentHasOptionalsubjectDao extends GenericDAO<StudentHasOptionalsubject,  StudentHasOptionalsubjectPK>  {
	// constructor only
}

