package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.Subject;
 
/**
 * DAO interface for table: Subject.
 * @author autogenerated
 */
public interface SubjectDao extends GenericDAO<Subject,  Integer>  {
	// constructor only
}

