package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassSubjectHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassSubjectHasStaffHasRolePK.
 * @author autogenerated
 */
public interface ClassSubjectHasStaffHasRolePKDao extends GenericDAO<ClassSubjectHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

