package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModuleHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassroomModuleHasStaffHasRolePK.
 * @author autogenerated
 */
public interface ClassroomModuleHasStaffHasRolePKDao extends GenericDAO<ClassroomModuleHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

