package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubjectHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassroomSubjectHasStaffHasRolePK.
 * @author autogenerated
 */
public interface ClassroomSubjectHasStaffHasRolePKDao extends GenericDAO<ClassroomSubjectHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

