package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomStudent;
 
/**
 * DAO interface for table: ClassroomStudent.
 * @author autogenerated
 */
public interface ClassroomStudentDao extends GenericDAO<ClassroomStudent,  Integer>  {
	// constructor only
}

