package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModule;
 
/**
 * DAO interface for table: ClassroomModule.
 * @author autogenerated
 */
public interface ClassroomModuleDao extends GenericDAO<ClassroomModule,  Integer>  {
	// constructor only
}

