package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModuleHasStaffHasRole;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModuleHasStaffHasRolePK;
/**
 * DAO interface for table: ClassroomModuleHasStaffHasRole.
 * @author autogenerated
 */
public interface ClassroomModuleHasStaffHasRoleDao extends GenericDAO<ClassroomModuleHasStaffHasRole,  ClassroomModuleHasStaffHasRolePK>  {
	// constructor only
}

