package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassroomHasStaffHasRolePK.
 * @author autogenerated
 */
public interface ClassroomHasStaffHasRolePKDao extends GenericDAO<ClassroomHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

