package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassSubject;
 
/**
 * DAO interface for table: ClassSubject.
 * @author autogenerated
 */
public interface ClassSubjectDao extends GenericDAO<ClassSubject,  Integer>  {
	// constructor only
}

