package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubject;
 
/**
 * DAO interface for table: ClassroomSubject.
 * @author autogenerated
 */
public interface ClassroomSubjectDao extends GenericDAO<ClassroomSubject,  Integer>  {
	// constructor only
}

