package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubjectHasStaffHasRole;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubjectHasStaffHasRolePK;
/**
 * DAO interface for table: ClassroomSubjectHasStaffHasRole.
 * @author autogenerated
 */
public interface ClassroomSubjectHasStaffHasRoleDao extends GenericDAO<ClassroomSubjectHasStaffHasRole,  ClassroomSubjectHasStaffHasRolePK>  {
	// constructor only
}

