package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassAnalyzerClassifier;
 
/**
 * DAO interface for table: ClassAnalyzerClassifier.
 * @author autogenerated
 */
public interface ClassAnalyzerClassifierDao extends GenericDAO<ClassAnalyzerClassifier,  Integer>  {
	// constructor only
}

