package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Division;
 
/**
 * DAO interface for table: Division.
 * @author autogenerated
 */
public interface DivisionDao extends GenericDAO<Division,  Integer>  {
	// constructor only
}

