package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ExamSync;
 
/**
 * DAO interface for table: ExamSync.
 * @author autogenerated
 */
public interface ExamSyncDao extends GenericDAO<ExamSync,  Integer>  {
	// constructor only
}

