package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ExamSyncPK;
import java.io.Serializable;
/**
 * DAO interface for table: ExamSyncPK.
 * @author autogenerated
 */
public interface ExamSyncPKDao extends GenericDAO<ExamSyncPK,  Serializable>  {
	// constructor only
}

