package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Exam;
 
/**
 * DAO interface for table: Exam.
 * @author autogenerated
 */
public interface ExamDao extends GenericDAO<Exam,  Integer>  {
	// constructor only
}

