package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Grade;
 
/**
 * DAO interface for table: Grade.
 * @author autogenerated
 */
public interface GradeDao extends GenericDAO<Grade,  Integer>  {
	// constructor only
}

