package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Marks;
 
/**
 * DAO interface for table: Marks.
 * @author autogenerated
 */
public interface MarksDao extends GenericDAO<Marks,  Integer>  {
	// constructor only
}

