package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Module;
 
/**
 * DAO interface for table: Module.
 * @author autogenerated
 */
public interface ModuleDao extends GenericDAO<Module,  Integer>  {
	// constructor only
}

