package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Results;
 
/**
 * DAO interface for table: Results.
 * @author autogenerated
 */
public interface ResultsDao extends GenericDAO<Results,  Integer>  {
	// constructor only
}

