package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.ResultsRank;
 
/**
 * DAO interface for table: ResultsRank.
 * @author autogenerated
 */
public interface ResultsRankDao extends GenericDAO<ResultsRank,  Integer>  {
	// constructor only
}

