package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.SchoolHasStaffHasRole;
import org.yarlithub.yschool.repository.model.obj.yschool.SchoolHasStaffHasRolePK;
/**
 * DAO interface for table: SchoolHasStaffHasRole.
 * @author autogenerated
 */
public interface SchoolHasStaffHasRoleDao extends GenericDAO<SchoolHasStaffHasRole,  SchoolHasStaffHasRolePK>  {
	// constructor only
}

