package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.SectionHasStaffHasRole;
import org.yarlithub.yschool.repository.model.obj.yschool.SectionHasStaffHasRolePK;
/**
 * DAO interface for table: SectionHasStaffHasRole.
 * @author autogenerated
 */
public interface SectionHasStaffHasRoleDao extends GenericDAO<SectionHasStaffHasRole,  SectionHasStaffHasRolePK>  {
	// constructor only
}

