package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Section;
 
/**
 * DAO interface for table: Section.
 * @author autogenerated
 */
public interface SectionDao extends GenericDAO<Section,  Integer>  {
	// constructor only
}

