package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StaffHasRole;
 
/**
 * DAO interface for table: StaffHasRole.
 * @author autogenerated
 */
public interface StaffHasRoleDao extends GenericDAO<StaffHasRole,  Integer>  {
	// constructor only
}

