package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentClassroomModule;
 
/**
 * DAO interface for table: StudentClassroomModule.
 * @author autogenerated
 */
public interface StudentClassroomModuleDao extends GenericDAO<StudentClassroomModule,  Integer>  {
	// constructor only
}

