package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentClassSubject;
 
/**
 * DAO interface for table: StudentClassSubject.
 * @author autogenerated
 */
public interface StudentClassSubjectDao extends GenericDAO<StudentClassSubject,  Integer>  {
	// constructor only
}

