package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentGeneralexamProfile;
 
/**
 * DAO interface for table: StudentGeneralexamProfile.
 * @author autogenerated
 */
public interface StudentGeneralexamProfileDao extends GenericDAO<StudentGeneralexamProfile,  Integer>  {
	// constructor only
}

