package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentSync;
 
/**
 * DAO interface for table: StudentSync.
 * @author autogenerated
 */
public interface StudentSyncDao extends GenericDAO<StudentSync,  Integer>  {
	// constructor only
}

