package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentSyncPK;
import java.io.Serializable;
/**
 * DAO interface for table: StudentSyncPK.
 * @author autogenerated
 */
public interface StudentSyncPKDao extends GenericDAO<StudentSyncPK,  Serializable>  {
	// constructor only
}

