package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentClassroomSubject;
 
/**
 * DAO interface for table: StudentClassroomSubject.
 * @author autogenerated
 */
public interface StudentClassroomSubjectDao extends GenericDAO<StudentClassroomSubject,  Integer>  {
	// constructor only
}

