package org.yarlithub.yschool.repository.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.repository.model.obj.yschool.Subject;
 
/**
 * DAO interface for table: Subject.
 * @author autogenerated
 */
public interface SubjectDao extends GenericDAO<Subject,  Integer>  {
	// constructor only
}

