package org.yarlithub.yschool.factories.yschoolLite;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import org.yarlithub.yschool.model.dao.yschoolLite.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateYschoolLiteDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateYschoolLiteDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateYschoolLiteDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateYschoolLiteDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a ClassStaffDao instance.
	 * 
	 * @return a ClassStaffDao instance
	 */
	public static ClassStaffDao getClassStaffDao() {
		return (ClassStaffDao) getBean("classStaffDaoImpl"); 
	}
	/**
	 * Returns a ClassStudentDao instance.
	 * 
	 * @return a ClassStudentDao instance
	 */
	public static ClassStudentDao getClassStudentDao() {
		return (ClassStudentDao) getBean("classStudentDaoImpl"); 
	}
	/**
	 * Returns a ClassSubjectDao instance.
	 * 
	 * @return a ClassSubjectDao instance
	 */
	public static ClassSubjectDao getClassSubjectDao() {
		return (ClassSubjectDao) getBean("classSubjectDaoImpl"); 
	}
	/**
	 * Returns a ClassroomDao instance.
	 * 
	 * @return a ClassroomDao instance
	 */
	public static ClassroomDao getClassroomDao() {
		return (ClassroomDao) getBean("classroomDaoImpl"); 
	}
	/**
	 * Returns a ExamDao instance.
	 * 
	 * @return a ExamDao instance
	 */
	public static ExamDao getExamDao() {
		return (ExamDao) getBean("examDaoImpl"); 
	}
	/**
	 * Returns a MarksDao instance.
	 * 
	 * @return a MarksDao instance
	 */
	public static MarksDao getMarksDao() {
		return (MarksDao) getBean("marksDaoImpl"); 
	}
	/**
	 * Returns a SchoolDao instance.
	 * 
	 * @return a SchoolDao instance
	 */
	public static SchoolDao getSchoolDao() {
		return (SchoolDao) getBean("schoolDaoImpl"); 
	}
	/**
	 * Returns a StaffDao instance.
	 * 
	 * @return a StaffDao instance
	 */
	public static StaffDao getStaffDao() {
		return (StaffDao) getBean("staffDaoImpl"); 
	}
	/**
	 * Returns a StudentDao instance.
	 * 
	 * @return a StudentDao instance
	 */
	public static StudentDao getStudentDao() {
		return (StudentDao) getBean("studentDaoImpl"); 
	}
	/**
	 * Returns a StudentHasOptionalsubjectDao instance.
	 * 
	 * @return a StudentHasOptionalsubjectDao instance
	 */
	public static StudentHasOptionalsubjectDao getStudentHasOptionalsubjectDao() {
		return (StudentHasOptionalsubjectDao) getBean("studentHasOptionalsubjectDaoImpl"); 
	}
	/**
	 * Returns a SubjectDao instance.
	 * 
	 * @return a SubjectDao instance
	 */
	public static SubjectDao getSubjectDao() {
		return (SubjectDao) getBean("subjectDaoImpl"); 
	}
	/**
	 * Returns a UserDao instance.
	 * 
	 * @return a UserDao instance
	 */
	public static UserDao getUserDao() {
		return (UserDao) getBean("userDaoImpl"); 
	}

}
