package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.ClassSubjectHasStaffHasRole;
import org.yarlithub.yschool.model.obj.yschool.ClassSubjectHasStaffHasRolePK;
/**
 * DAO interface for table: ClassSubjectHasStaffHasRole.
 * @author autogenerated
 */
public interface ClassSubjectHasStaffHasRoleDao extends GenericDAO<ClassSubjectHasStaffHasRole,  ClassSubjectHasStaffHasRolePK>  {
	// constructor only
}

