package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.ClassStudent;
 
/**
 * DAO interface for table: ClassStudent.
 * @author autogenerated
 */
public interface ClassStudentDao extends GenericDAO<ClassStudent,  Integer>  {
	// constructor only
}

