package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.ClassroomHasStaffHasRole;
import org.yarlithub.yschool.model.obj.yschool.ClassroomHasStaffHasRolePK;
/**
 * DAO interface for table: ClassroomHasStaffHasRole.
 * @author autogenerated
 */
public interface ClassroomHasStaffHasRoleDao extends GenericDAO<ClassroomHasStaffHasRole,  ClassroomHasStaffHasRolePK>  {
	// constructor only
}

