package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.ExamType;
 
/**
 * DAO interface for table: ExamType.
 * @author autogenerated
 */
public interface ExamTypeDao extends GenericDAO<ExamType,  Integer>  {
	// constructor only
}

