package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.Role;
 
/**
 * DAO interface for table: Role.
 * @author autogenerated
 */
public interface RoleDao extends GenericDAO<Role,  Integer>  {
	// constructor only
}

