package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.SchoolHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: SchoolHasStaffHasRolePK.
 * @author autogenerated
 */
public interface SchoolHasStaffHasRolePKDao extends GenericDAO<SchoolHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

