package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.Staff;
 
/**
 * DAO interface for table: Staff.
 * @author autogenerated
 */
public interface StaffDao extends GenericDAO<Staff,  Integer>  {
	// constructor only
}

