package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.Student;
 
/**
 * DAO interface for table: Student.
 * @author autogenerated
 */
public interface StudentDao extends GenericDAO<Student,  Integer>  {
	// constructor only
}

