package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.User;
 
/**
 * DAO interface for table: User.
 * @author autogenerated
 */
public interface UserDao extends GenericDAO<User,  Integer>  {
	// constructor only
}

