package org.yarlithub.yschool.model.dao.yschool;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschool.UserRole;
 
/**
 * DAO interface for table: UserRole.
 * @author autogenerated
 */
public interface UserRoleDao extends GenericDAO<UserRole,  Integer>  {
	// constructor only
}

