package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.Classroom;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomDao;
 
 
/**
 * DAO for table: Classroom.
 * @author autogenerated
 */
@Repository
public class ClassroomDaoImpl extends GenericHibernateDaoImpl<Classroom, Integer> implements ClassroomDao {
	
	/** Constructor method. */
		public ClassroomDaoImpl() {
			super(Classroom.class);
		}
	}

