package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassSubjectHasStaffHasRolePK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassSubjectHasStaffHasRolePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ClassSubjectHasStaffHasRolePK.
 * @author autogenerated
 */
@Repository
public class ClassSubjectHasStaffHasRolePKDaoImpl extends GenericHibernateDaoImpl<ClassSubjectHasStaffHasRolePK, Serializable> implements ClassSubjectHasStaffHasRolePKDao {
	
	/** Constructor method. */
		public ClassSubjectHasStaffHasRolePKDaoImpl() {
			super(ClassSubjectHasStaffHasRolePK.class);
		}
	}

