package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassSubject;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassSubjectDao;
 
 
/**
 * DAO for table: ClassSubject.
 * @author autogenerated
 */
@Repository
public class ClassSubjectDaoImpl extends GenericHibernateDaoImpl<ClassSubject, Integer> implements ClassSubjectDao {
	
	/** Constructor method. */
		public ClassSubjectDaoImpl() {
			super(ClassSubject.class);
		}
	}

