package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomStudent;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomStudentDao;
 
 
/**
 * DAO for table: ClassroomStudent.
 * @author autogenerated
 */
@Repository
public class ClassroomStudentDaoImpl extends GenericHibernateDaoImpl<ClassroomStudent, Integer> implements ClassroomStudentDao {
	
	/** Constructor method. */
		public ClassroomStudentDaoImpl() {
			super(ClassroomStudent.class);
		}
	}

