package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModule;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomModuleDao;
 
 
/**
 * DAO for table: ClassroomModule.
 * @author autogenerated
 */
@Repository
public class ClassroomModuleDaoImpl extends GenericHibernateDaoImpl<ClassroomModule, Integer> implements ClassroomModuleDao {
	
	/** Constructor method. */
		public ClassroomModuleDaoImpl() {
			super(ClassroomModule.class);
		}
	}

