package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubjectHasStaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomSubjectHasStaffHasRoleDao;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubjectHasStaffHasRolePK;
 
/**
 * DAO for table: ClassroomSubjectHasStaffHasRole.
 * @author autogenerated
 */
@Repository
public class ClassroomSubjectHasStaffHasRoleDaoImpl extends GenericHibernateDaoImpl<ClassroomSubjectHasStaffHasRole, ClassroomSubjectHasStaffHasRolePK> implements ClassroomSubjectHasStaffHasRoleDao {
	
	/** Constructor method. */
		public ClassroomSubjectHasStaffHasRoleDaoImpl() {
			super(ClassroomSubjectHasStaffHasRole.class);
		}
	}

