package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModuleHasStaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomModuleHasStaffHasRoleDao;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomModuleHasStaffHasRolePK;
 
/**
 * DAO for table: ClassroomModuleHasStaffHasRole.
 * @author autogenerated
 */
@Repository
public class ClassroomModuleHasStaffHasRoleDaoImpl extends GenericHibernateDaoImpl<ClassroomModuleHasStaffHasRole, ClassroomModuleHasStaffHasRolePK> implements ClassroomModuleHasStaffHasRoleDao {
	
	/** Constructor method. */
		public ClassroomModuleHasStaffHasRoleDaoImpl() {
			super(ClassroomModuleHasStaffHasRole.class);
		}
	}

