package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomHasStaffHasRolePK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomHasStaffHasRolePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ClassroomHasStaffHasRolePK.
 * @author autogenerated
 */
@Repository
public class ClassroomHasStaffHasRolePKDaoImpl extends GenericHibernateDaoImpl<ClassroomHasStaffHasRolePK, Serializable> implements ClassroomHasStaffHasRolePKDao {
	
	/** Constructor method. */
		public ClassroomHasStaffHasRolePKDaoImpl() {
			super(ClassroomHasStaffHasRolePK.class);
		}
	}

