package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomSubjectHasStaffHasRolePK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomSubjectHasStaffHasRolePKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ClassroomSubjectHasStaffHasRolePK.
 * @author autogenerated
 */
@Repository
public class ClassroomSubjectHasStaffHasRolePKDaoImpl extends GenericHibernateDaoImpl<ClassroomSubjectHasStaffHasRolePK, Serializable> implements ClassroomSubjectHasStaffHasRolePKDao {
	
	/** Constructor method. */
		public ClassroomSubjectHasStaffHasRolePKDaoImpl() {
			super(ClassroomSubjectHasStaffHasRolePK.class);
		}
	}

