package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomHasStaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassroomHasStaffHasRoleDao;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassroomHasStaffHasRolePK;
 
/**
 * DAO for table: ClassroomHasStaffHasRole.
 * @author autogenerated
 */
@Repository
public class ClassroomHasStaffHasRoleDaoImpl extends GenericHibernateDaoImpl<ClassroomHasStaffHasRole, ClassroomHasStaffHasRolePK> implements ClassroomHasStaffHasRoleDao {
	
	/** Constructor method. */
		public ClassroomHasStaffHasRoleDaoImpl() {
			super(ClassroomHasStaffHasRole.class);
		}
	}

