package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ClassAnalyzerClassifier;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ClassAnalyzerClassifierDao;
 
 
/**
 * DAO for table: ClassAnalyzerClassifier.
 * @author autogenerated
 */
@Repository
public class ClassAnalyzerClassifierDaoImpl extends GenericHibernateDaoImpl<ClassAnalyzerClassifier, Integer> implements ClassAnalyzerClassifierDao {
	
	/** Constructor method. */
		public ClassAnalyzerClassifierDaoImpl() {
			super(ClassAnalyzerClassifier.class);
		}
	}

