package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.Division;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.DivisionDao;
 
 
/**
 * DAO for table: Division.
 * @author autogenerated
 */
@Repository
public class DivisionDaoImpl extends GenericHibernateDaoImpl<Division, Integer> implements DivisionDao {
	
	/** Constructor method. */
		public DivisionDaoImpl() {
			super(Division.class);
		}
	}

