package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ExamSyncPK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ExamSyncPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ExamSyncPK.
 * @author autogenerated
 */
@Repository
public class ExamSyncPKDaoImpl extends GenericHibernateDaoImpl<ExamSyncPK, Serializable> implements ExamSyncPKDao {
	
	/** Constructor method. */
		public ExamSyncPKDaoImpl() {
			super(ExamSyncPK.class);
		}
	}

