package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ExamSync;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ExamSyncDao;
import org.yarlithub.yschool.repository.model.obj.yschool.ExamSyncPK;
 
/**
 * DAO for table: ExamSync.
 * @author autogenerated
 */
@Repository
public class ExamSyncDaoImpl extends GenericHibernateDaoImpl<ExamSync, ExamSyncPK> implements ExamSyncDao {
	
	/** Constructor method. */
		public ExamSyncDaoImpl() {
			super(ExamSync.class);
		}
	}

