package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.Grade;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.GradeDao;
 
 
/**
 * DAO for table: Grade.
 * @author autogenerated
 */
@Repository
public class GradeDaoImpl extends GenericHibernateDaoImpl<Grade, Integer> implements GradeDao {
	
	/** Constructor method. */
		public GradeDaoImpl() {
			super(Grade.class);
		}
	}

