package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.Module;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ModuleDao;
 
 
/**
 * DAO for table: Module.
 * @author autogenerated
 */
@Repository
public class ModuleDaoImpl extends GenericHibernateDaoImpl<Module, Integer> implements ModuleDao {
	
	/** Constructor method. */
		public ModuleDaoImpl() {
			super(Module.class);
		}
	}

