package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.ResultsRank;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.ResultsRankDao;
 
 
/**
 * DAO for table: ResultsRank.
 * @author autogenerated
 */
@Repository
public class ResultsRankDaoImpl extends GenericHibernateDaoImpl<ResultsRank, Integer> implements ResultsRankDao {
	
	/** Constructor method. */
		public ResultsRankDaoImpl() {
			super(ResultsRank.class);
		}
	}

