package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.School;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.SchoolDao;
 
 
/**
 * DAO for table: School.
 * @author autogenerated
 */
@Repository
public class SchoolDaoImpl extends GenericHibernateDaoImpl<School, Integer> implements SchoolDao {
	
	/** Constructor method. */
		public SchoolDaoImpl() {
			super(School.class);
		}
	}

