package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.Section;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.SectionDao;
 
 
/**
 * DAO for table: Section.
 * @author autogenerated
 */
@Repository
public class SectionDaoImpl extends GenericHibernateDaoImpl<Section, Integer> implements SectionDao {
	
	/** Constructor method. */
		public SectionDaoImpl() {
			super(Section.class);
		}
	}

