package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.StaffHasRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.StaffHasRoleDao;
 
 
/**
 * DAO for table: StaffHasRole.
 * @author autogenerated
 */
@Repository
public class StaffHasRoleDaoImpl extends GenericHibernateDaoImpl<StaffHasRole, Integer> implements StaffHasRoleDao {
	
	/** Constructor method. */
		public StaffHasRoleDaoImpl() {
			super(StaffHasRole.class);
		}
	}

