package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentSync;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.StudentSyncDao;
 
 
/**
 * DAO for table: StudentSync.
 * @author autogenerated
 */
@Repository
public class StudentSyncDaoImpl extends GenericHibernateDaoImpl<StudentSync, Integer> implements StudentSyncDao {
	
	/** Constructor method. */
		public StudentSyncDaoImpl() {
			super(StudentSync.class);
		}
	}

