package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentClassroomSubject;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.StudentClassroomSubjectDao;
 
 
/**
 * DAO for table: StudentClassroomSubject.
 * @author autogenerated
 */
@Repository
public class StudentClassroomSubjectDaoImpl extends GenericHibernateDaoImpl<StudentClassroomSubject, Integer> implements StudentClassroomSubjectDao {
	
	/** Constructor method. */
		public StudentClassroomSubjectDaoImpl() {
			super(StudentClassroomSubject.class);
		}
	}

