package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentClassroomModule;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.StudentClassroomModuleDao;
 
 
/**
 * DAO for table: StudentClassroomModule.
 * @author autogenerated
 */
@Repository
public class StudentClassroomModuleDaoImpl extends GenericHibernateDaoImpl<StudentClassroomModule, Integer> implements StudentClassroomModuleDao {
	
	/** Constructor method. */
		public StudentClassroomModuleDaoImpl() {
			super(StudentClassroomModule.class);
		}
	}

