package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentSyncPK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.StudentSyncPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: StudentSyncPK.
 * @author autogenerated
 */
@Repository
public class StudentSyncPKDaoImpl extends GenericHibernateDaoImpl<StudentSyncPK, Serializable> implements StudentSyncPKDao {
	
	/** Constructor method. */
		public StudentSyncPKDaoImpl() {
			super(StudentSyncPK.class);
		}
	}

