package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.StudentGeneralexamProfile;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.StudentGeneralexamProfileDao;
 
 
/**
 * DAO for table: StudentGeneralexamProfile.
 * @author autogenerated
 */
@Repository
public class StudentGeneralexamProfileDaoImpl extends GenericHibernateDaoImpl<StudentGeneralexamProfile, Integer> implements StudentGeneralexamProfileDao {
	
	/** Constructor method. */
		public StudentGeneralexamProfileDaoImpl() {
			super(StudentGeneralexamProfile.class);
		}
	}

