package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.UserRole;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.UserRoleDao;
 
 
/**
 * DAO for table: UserRole.
 * @author autogenerated
 */
@Repository
public class UserRoleDaoImpl extends GenericHibernateDaoImpl<UserRole, Integer> implements UserRoleDao {
	
	/** Constructor method. */
		public UserRoleDaoImpl() {
			super(UserRole.class);
		}
	}

