package org.yarlithub.yschool.repository.model.dao.yschool.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.repository.model.obj.yschool.User;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.repository.model.dao.yschool.UserDao;
 
 
/**
 * DAO for table: User.
 * @author autogenerated
 */
@Repository
public class UserDaoImpl extends GenericHibernateDaoImpl<User, Integer> implements UserDao {
	
	/** Constructor method. */
		public UserDaoImpl() {
			super(User.class);
		}
	}

