package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassSubjectHasStaffHasRole;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassSubjectHasStaffHasRolePK;
/**
 * DAO interface for table: ClassSubjectHasStaffHasRole.
 * @author autogenerated
 */
public interface ClassSubjectHasStaffHasRoleDao extends GenericDAO<ClassSubjectHasStaffHasRole,  ClassSubjectHasStaffHasRolePK>  {
	// constructor only
}

