package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaffPK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassStaffPK.
 * @author autogenerated
 */
public interface ClassStaffPKDao extends GenericDAO<ClassStaffPK,  Serializable>  {
	// constructor only
}

