package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassSubject;
 
/**
 * DAO interface for table: ClassSubject.
 * @author autogenerated
 */
public interface ClassSubjectDao extends GenericDAO<ClassSubject,  Integer>  {
	// constructor only
}

