package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassSubjectHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: ClassSubjectHasStaffHasRolePK.
 * @author autogenerated
 */
public interface ClassSubjectHasStaffHasRolePKDao extends GenericDAO<ClassSubjectHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

