package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.Exam;
 
/**
 * DAO interface for table: Exam.
 * @author autogenerated
 */
public interface ExamDao extends GenericDAO<Exam,  Integer>  {
	// constructor only
}

