package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.Role;
 
/**
 * DAO interface for table: Role.
 * @author autogenerated
 */
public interface RoleDao extends GenericDAO<Role,  Integer>  {
	// constructor only
}

