package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.SchoolHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: SchoolHasStaffHasRolePK.
 * @author autogenerated
 */
public interface SchoolHasStaffHasRolePKDao extends GenericDAO<SchoolHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

