package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.SectionHasStaffHasRole;
import org.yarlithub.yschool.model.obj.yschoolLite.SectionHasStaffHasRolePK;
/**
 * DAO interface for table: SectionHasStaffHasRole.
 * @author autogenerated
 */
public interface SectionHasStaffHasRoleDao extends GenericDAO<SectionHasStaffHasRole,  SectionHasStaffHasRolePK>  {
	// constructor only
}

