package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.SectionHasStaffHasRolePK;
import java.io.Serializable;
/**
 * DAO interface for table: SectionHasStaffHasRolePK.
 * @author autogenerated
 */
public interface SectionHasStaffHasRolePKDao extends GenericDAO<SectionHasStaffHasRolePK,  Serializable>  {
	// constructor only
}

