package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.Section;
 
/**
 * DAO interface for table: Section.
 * @author autogenerated
 */
public interface SectionDao extends GenericDAO<Section,  Integer>  {
	// constructor only
}

