package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.StaffHasRole;
 
/**
 * DAO interface for table: StaffHasRole.
 * @author autogenerated
 */
public interface StaffHasRoleDao extends GenericDAO<StaffHasRole,  Integer>  {
	// constructor only
}

