package org.yarlithub.yschool.model.dao.yschoolLite;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubjectPK;
import java.io.Serializable;
/**
 * DAO interface for table: StudentHasOptionalsubjectPK.
 * @author autogenerated
 */
public interface StudentHasOptionalsubjectPKDao extends GenericDAO<StudentHasOptionalsubjectPK,  Serializable>  {
	// constructor only
}

