package org.yarlithub.yschool.services.data;

import java.io.Serializable;
import org.yarlithub.yschool.model.obj.yschoolLite.Classroom;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaff;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaffPK;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudent;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudentPK;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassSubject;
import org.yarlithub.yschool.model.obj.yschoolLite.Exam;
import org.yarlithub.yschool.model.obj.yschoolLite.Marks;
import org.yarlithub.yschool.model.obj.yschoolLite.School;
import org.yarlithub.yschool.model.obj.yschoolLite.Staff;
import org.yarlithub.yschool.model.obj.yschoolLite.Student;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubject;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubjectPK;
import org.yarlithub.yschool.model.obj.yschoolLite.Subject;
import org.yarlithub.yschool.model.obj.yschoolLite.User;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.ReplicationMode;
import org.hibernate.Session;
import java.util.Collection;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
/** 
 * Data layer.
 * @author autogenerated
 */
public interface DataLayerYschoolLite {

    /**
     * Deletes the given object from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to delete
     */
    <T> void delete(T persistentObject);
    /**
     * Refresh the object $class.className from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to reload
     */
    <T> void refresh(T persistentObject);

    /**
     * Saves the given object to disk.
     * @param persistentObject Object to save
	 * @param <T> A DataLayerObject-derived type
     * @return Identifier of saved object 
     */
    <T> Serializable save(T persistentObject);
    /**
     * Saves or updates the given $class.className object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to save 
     */
    <T> void saveOrUpdate(T persistentObject);
    /**
     * Updates the given object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to update 
     */
    <T> void update(T persistentObject);


    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Classroom obj) directly
     * @param id Identifier to delete
     */
    void deleteClassroom(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Classroom object
     */
    Classroom loadClassroom(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Classroom getClassroom(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ClassStaff obj) directly
     * @param id Identifier to delete
     */
    void deleteClassStaff(final ClassStaffPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ClassStaff object
     */
    ClassStaff loadClassStaff(final ClassStaffPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ClassStaff getClassStaff(final ClassStaffPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ClassStudent obj) directly
     * @param id Identifier to delete
     */
    void deleteClassStudent(final ClassStudentPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ClassStudent object
     */
    ClassStudent loadClassStudent(final ClassStudentPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ClassStudent getClassStudent(final ClassStudentPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ClassSubject obj) directly
     * @param id Identifier to delete
     */
    void deleteClassSubject(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ClassSubject object
     */
    ClassSubject loadClassSubject(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ClassSubject getClassSubject(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Exam obj) directly
     * @param id Identifier to delete
     */
    void deleteExam(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Exam object
     */
    Exam loadExam(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Exam getExam(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Marks obj) directly
     * @param id Identifier to delete
     */
    void deleteMarks(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Marks object
     */
    Marks loadMarks(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Marks getMarks(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (School obj) directly
     * @param id Identifier to delete
     */
    void deleteSchool(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a School object
     */
    School loadSchool(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     School getSchool(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Staff obj) directly
     * @param id Identifier to delete
     */
    void deleteStaff(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Staff object
     */
    Staff loadStaff(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Staff getStaff(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Student obj) directly
     * @param id Identifier to delete
     */
    void deleteStudent(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Student object
     */
    Student loadStudent(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Student getStudent(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (StudentHasOptionalsubject obj) directly
     * @param id Identifier to delete
     */
    void deleteStudentHasOptionalsubject(final StudentHasOptionalsubjectPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a StudentHasOptionalsubject object
     */
    StudentHasOptionalsubject loadStudentHasOptionalsubject(final StudentHasOptionalsubjectPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     StudentHasOptionalsubject getStudentHasOptionalsubject(final StudentHasOptionalsubjectPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Subject obj) directly
     * @param id Identifier to delete
     */
    void deleteSubject(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Subject object
     */
    Subject loadSubject(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Subject getSubject(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (User obj) directly
     * @param id Identifier to delete
     */
    void deleteUser(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a User object
     */
    User loadUser(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     User getUser(final Integer id);  
    /** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     Query createQuery(final String query);
    /** Returns a criteria handle.
     * @param criteria Criteria to use
     * @return A criteria instance
     */
     Criteria createCriteria(final String criteria);
    /** Returns a Query handle based on your package-level named query.
     * @param query Query to use
     * @return A query instance
     */
     Query getNamedQuery(final String query);
    /** Create a new Criteria instance, for the given entity class, or a superclass of an entity class.
	* @param persistentObject a class, which is persistent, or has persistent subclasses 
	* @return Criteria instance
	*/
	@SuppressWarnings("rawtypes")
	Criteria createCriteria(Class persistentObject);
    /** Flushes the currently open session.
	*/
	void flushSession();
    /** Clears the currently open session.
	*/
	void clearSession();
    /** Flushes and clears the currently open session.
	*/
	void flushAndClearSession();
	/** Call currentSession.replicate.
	 * @param obj to replicate
	 * @param replicationMode mode
	 */ 
	void replicate(Object obj, ReplicationMode replicationMode);
	/** Hibernate Merge. 
	 * @param obj to merge
	 * @return obj merged.
	 */
	Object merge(Object obj);
	/** Returns the current session.
	 * @return the currently active session
	 */
	Session getCurrentSession();
	/** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     SQLQuery createSQLQuery(final String query);
    /** Remove this instance from the session cache. 
	 * Changes to the instance will not be synchronized with the database
	 * @param obj object to evict
	 */
	void evict(Object obj);
    /**
     * Return the persistent instance of the given entity class with the given 
     * identifier, or null if there is no such persistent instance. 
     * (If the instance, or a proxy for the instance, is already 
     * associated with the session, return that instance or proxy)
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return a persistent instance or null
     * @throws HibernateException
     */
	Object get(Class<?> clazz, Serializable id) throws HibernateException;	


    /**
     * Return the persistent instance of the given entity class with the given identifier, assuming that the instance exists.
     *You should not use this method to determine if an instance exists (use get() instead). Use this only to retrieve an instance that you assume exists, where non-existence would be an actual error.
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return the persistent instance or proxy
     * @throws HibernateException
     */
	Object load(Class<?> clazz, Serializable id) throws HibernateException;
	/**
	 * Reattaches the given entity to the current session using LockMode.NONE
	 *
	 * @param entity to reattach
	 */
	void reattachEntityWithNoLock(IPojoGenEntity entity);
	/**
	 * Reattaches the given entities to the current session.
	 *
	 * @param entities to attach
	 */
	void reattachEntitiesWithNoLock(Collection<? extends IPojoGenEntity> entities);}

