package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStudentPK;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.ClassStudentPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ClassStudentPK.
 * @author autogenerated
 */
@Repository
public class ClassStudentPKDaoImpl extends GenericHibernateDaoImpl<ClassStudentPK, Serializable> implements ClassStudentPKDao {
	
	/** Constructor method. */
		public ClassStudentPKDaoImpl() {
			super(ClassStudentPK.class);
		}
	}

