package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaff;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.ClassStaffDao;
import org.yarlithub.yschool.model.obj.yschoolLite.ClassStaffPK;
 
/**
 * DAO for table: ClassStaff.
 * @author autogenerated
 */
@Repository
public class ClassStaffDaoImpl extends GenericHibernateDaoImpl<ClassStaff, ClassStaffPK> implements ClassStaffDao {
	
	/** Constructor method. */
		public ClassStaffDaoImpl() {
			super(ClassStaff.class);
		}
	}

