package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.School;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.SchoolDao;
 
 
/**
 * DAO for table: School.
 * @author autogenerated
 */
@Repository
public class SchoolDaoImpl extends GenericHibernateDaoImpl<School, Integer> implements SchoolDao {
	
	/** Constructor method. */
		public SchoolDaoImpl() {
			super(School.class);
		}
	}

