package org.yarlithub.yschool.model.dao.yschoolLite.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubject;
import org.springframework.stereotype.Repository;
import org.yarlithub.yschool.model.dao.yschoolLite.StudentHasOptionalsubjectDao;
import org.yarlithub.yschool.model.obj.yschoolLite.StudentHasOptionalsubjectPK;
 
/**
 * DAO for table: StudentHasOptionalsubject.
 * @author autogenerated
 */
@Repository
public class StudentHasOptionalsubjectDaoImpl extends GenericHibernateDaoImpl<StudentHasOptionalsubject, StudentHasOptionalsubjectPK> implements StudentHasOptionalsubjectDao {
	
	/** Constructor method. */
		public StudentHasOptionalsubjectDaoImpl() {
			super(StudentHasOptionalsubject.class);
		}
	}

