package org.yarlithub.yschool.repository.enums.subtype.yschool;
/**
 * Defines the ResultsSubclassType enumeration.
 * 
 * @author autogenerated
 *
 */
public enum ResultsSubclassType {

	/** Enum Constant. */
	NOT_A_CHILD,
	/** Enum Constant. */
	RESULTS_RANK;

}
